ハンズオン手順についてつまりどころを解消するように修正
raisetech-for-student/git-hands-on pull request #4
Opened 2023-08-25 01:58 UTC by yoshi-koyama

# 背景

Git/GitHubのハンズオンを実施するにあたりpushまわりでつまずいてしまう人が多い。
作成意図としてはpushまわりでつまずいてもらい、調査してもらうことを目的にしていたが、あまりにも調査時間がかかっているように見受けられる。
pushできなくて嫌になって学習を止めるというのは本末転倒なのでpushがスムーズにできるように資料を変更する。

# 修正したこと
- HTTPSでのpushをするように手順を変更
- PATの作成方法を例示
- push時の注意事項を追加
- チャットでの連絡はしないでよいように修正

# やっていないこと

Pull requestの作成までハンズオンでやってもいいと思う。
が、そこまでの手順を含めてしまうとこのPull requestが肥大化してしまうので対応しない。

# 参考資料

AWSコースメンターのミズモト大先生の資料を参考にしています。
https://github.com/MasatoshiMizumoto/raisetech_documents/blob/main/aws/docs/git_pullrequest_handson.md

2023-08-25 02:17 UTC, yoshi-koyama commented on README.md
> +WindowsでのWeb開発にWSL2は必要になりますが、インストールでつまってしまう場合、今はGitのみの利用なのでGit for Windowsをインストールしましょう。
WSL周りも詰まる人がおおい。
Dockerを使う段で解決できればよいのでここではGit for WindowsでもOKとする。

2023-08-25 02:17 UTC, yoshi-koyama commented on README.md
> +公式: https://git-scm.com/book/ja/v2/%E4%BD%BF%E3%81%84%E5%A7%8B%E3%82%81%E3%82%8B-%E6%9C%80%E5%88%9D%E3%81%AEGit%E3%81%AE%E6%A7%8B%E6%88%90
git config設定しないと初回のコミットができないはず。
ここもつまりつつも自己解決できるのがいいとは思うものの紹介しておいて良いかなと思うので追記。

2023-08-25 02:17 UTC, yoshi-koyama commented on README.md
> +| `classic`                             | リポジトリを条件に含められないので `repo`にチェック。    |
こちらはミズモトさんの資料の記載を拝借。

2023-08-25 02:17 UTC, yoshi-koyama commented on README.md
> +## GitHubにてリポジトリを作成
レポジトリをリポジトリに修正

2023-08-25 02:17 UTC, yoshi-koyama commented on README.md
> +## GitHubにてリポジトリを作成
ハンズオン作ったときまでずっとレポジトリだと思っていた。

2023-08-25 02:17 UTC, yoshi-koyama commented on README.md
> +`$`は入力しないでください。
地味に間違う人多いので注釈を追加

2023-08-25 02:17 UTC, yoshi-koyama commented on README.md
> +時間があるときでいいので`Windows ソースコード 置き場所`などで調べてみてください。
全角スペース -> 半角スペース

2023-08-25 02:17 UTC, yoshi-koyama commented on README.md
> +また、パスワードは入力しても表示されませんが、入力されています。
こちらもミズモトさんの資料から記載を拝借

2023-08-25 02:17 UTC, yoshi-koyama commented on README.md
> +$ pwd
全体的にコマンドについてシンタクスハイライトを使うように修正

2023-08-25 10:28 UTC, Shibata0806 requested changes
ありがとうございます🙇
いくつかコメントさせていただきました！

2023-08-25 10:28 UTC, Shibata0806 commented on README.md
> +を実行してgitのバージョン情報が表示されたらOKです。
@yoshi-koyama 

ここで、
> コマンドの先頭にある$はコマンドを実行することを意味します。
$は入力しないでください。

が既に記載されてても良いかもしれないと思いました！

2023-08-25 10:28 UTC, Shibata0806 commented on README.md
> +GitHub公式サイト: https://docs.github.com/ja/get-started/signing-up-for-github/signing-up-for-a-new-github-account
@yoshi-koyama 
36行目あたりに、「Githubのアカウント作成」というセクションがあってもいいかもしれないと思いました！

2023-08-25 10:28 UTC, Shibata0806 commented on README.md
> +なお、そのときにキャプチャの赤丸部分がHTTPSを選択していることに注意してください。
@yoshi-koyama 
> キャプチャの赤丸部分

ですが、キャプチャの中に赤丸がなさそうでした💦

2023-08-25 12:59 UTC, yoshi-koyama commented on README.md
> +を実行してgitのバージョン情報が表示されたらOKです。
たしかに。

2023-08-25 12:59 UTC, yoshi-koyama commented on README.md
> +を実行してgitのバージョン情報が表示されたらOKです。
対応しました！
571715515a8acfe7b1c4c0e4dc1573acf418c4ab

2023-08-25 12:59 UTC, yoshi-koyama commented on README.md
> +GitHub公式サイト: https://docs.github.com/ja/get-started/signing-up-for-github/signing-up-for-a-new-github-account
アカウント作成セクションを設けました！
b7111e45e6ce2fb6e5be5a218354b1a8dd2bf40c

2023-08-25 13:01 UTC, yoshi-koyama commented on README.md
> +なお、そのときにキャプチャの赤丸部分がHTTPSを選択していることに注意してください。
これはこれは！！！
添付しました！
26f0ac2db35b50e424e50c6781eee91298d109fa

2023-08-25 13:01 UTC, yoshi-koyama commented on README.md
> +なお、そのときにキャプチャの赤丸部分がHTTPSを選択していることに注意してください。
<img width="840" alt="スクリーンショット 2023-08-25 22 01 20" src="https://github.com/raisetech-for-student/git-hands-on/assets/62045457/0c491ed1-3302-44f3-8df6-f34e7b98780a">

2023-08-25 13:15 UTC, kana2212 commented on README.md
> +公式: https://git-scm.com/book/ja/v2/%E4%BD%BF%E3%81%84%E5%A7%8B%E3%82%81%E3%82%8B-%E6%9C%80%E5%88%9D%E3%81%AEGit%E3%81%AE%E6%A7%8B%E6%88%90
git configは触るのが怖かった記憶があるので明示して頂けるのはとても助かります。

2023-08-25 13:19 UTC, yoshi-koyama commented on README.md
> +公式: https://git-scm.com/book/ja/v2/%E4%BD%BF%E3%81%84%E5%A7%8B%E3%82%81%E3%82%8B-%E6%9C%80%E5%88%9D%E3%81%AEGit%E3%81%AE%E6%A7%8B%E6%88%90
> git configは触るのが怖かった

そういうこともあるか。
たしかに。
とても参考になる意見です！！

2023-08-26 03:43 UTC, Shibata0806 approved these changes
ご対応ありがとうございます！
LGTMです！！

2023-08-26 04:53 UTC, ABECKCROW commented on README.md
> +`$`は入力しないでください。
地味に間違う人の1人で質問までしてしまったのでこの注釈はとても助かります。僕の時は％でしたが。

2023-08-26 07:36 UTC, yoshi-koyama commented on README.md
> +`$`は入力しないでください。
最初は間違いますよね 😓

2023-08-26 07:45 UTC, ABECKCROW approved these changes

2023-08-26 08:08 UTC, kana2212 approved these changes

2023-08-26 08:11 UTC, merged